### ISSUE TITLE
Modify other parameters (Quant Bytes)

### ISSUE THREAD

**Issue by wildlifechorus** [Griffin98/posenet_tfjs2tflite#1]
First of all, thank you so much for this! I've been looking for something to convert tfjs to tflite for a while now.

I was wondering if there's a way to also change the **Quant bytes** just like you do in tfjs.

Maybe if you point me in the right direction I might be able to contribute to this awesome repo :)

Another question I have is if you have in your plans to support ResNet in this script.

Many thanks!

**Comment by Griffin98** [comment]
You have two options to achieve it:
1) Download Model weights with different quant bytes , or,
2) Determine have to mutliple quant bytes with each layer while assembling( this will be tougher). For this good start can be from here: https://github.com/tensorflow/tfjs-models/blob/master/posenet/src/posenet_model.ts

My current repo uses Posenet 1.0 model checkpoints which are obsolete now. I have plan to upgrade my repo to use Posenet 2.0 models (latest checkpoints of MobileNet and ResNet architectures) (https://github.com/tensorflow/tfjs-models/blob/master/posenet/src/checkpoints.ts#L35). This upgrade will also includes configurable quant bytes parameter. Here is a good start, if you wish to implement it: https://github.com/atomicbits/posenet-python/tree/master/posenet/converter.

PS: Don't ask me ETA of the upgrade. It's in my TODO list.

**Comment by wildlifechorus** [comment]
Hey! Thanks for your answer. I just generated a couple of files with different multipliers and output strides. But it fails to load on iOS. Any idea why?

I just get `Failed to load the model file with name`
Default `threadCount` is 2

Here's one of the files: [https://drive.google.com/open?id=1ubHgqRi3Er9PxTiKvuSBzO97mbt4_fsl](https://drive.google.com/open?id=1ubHgqRi3Er9PxTiKvuSBzO97mbt4_fsl)
